# Generated by Django 3.0.5 on 2020-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_clube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_default.jpg', null=True, upload_to='clubs_logo/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_default.jpg', null=True, upload_to='page_logo/'),
        ),
    ]
